basePath: /api/v1
definitions:
  handler.User:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: stoola08@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is a get role server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GetRole API
  version: "1.0"
paths:
  /role:
    get:
      operationId: getRoles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.User'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
        "404":
          description: Not Found
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: Get all roles
      tags:
      - Role
  /role/:id:
    get:
      operationId: getRole
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.User'
        "400":
          description: Bad Request
          schema:
            type: ""
        "404":
          description: Not Found
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: Get one role based on ID
      tags:
      - Role
swagger: "2.0"
